export { SliderComparison } from './SliderComparison'
export { SideBySide } from './SideBySide'
export { BlendModes } from './BlendModes'
export { SplitScreen } from './SplitScreen'
export { FlickerComparison } from './FlickerComparison'
export { MetricsOverlay } from './MetricsOverlay'
export { PixelInspector } from './PixelInspector'
export { DifferenceHeatmap } from './DifferenceHeatmap'
export { MagnifierLoupe, useMagnifier } from './MagnifierLoupe'
export { WebGLComparison } from './WebGLComparison'
export { AudioComparison } from './AudioComparison'
// MODE-001 to MODE-005: New comparison modes
export { QuadComparison } from './QuadComparison'
export { RadialLoupeComparison } from './RadialLoupeComparison'
export { GridTileComparison } from './GridTileComparison'
export { PixelGridOverlay } from './PixelGridOverlay'
export { MorphologicalView } from './MorphologicalView'
// Document comparison components
